### ISSUE TITLE
Use GELF library v2

### ISSUE THREAD

**Issue by nettoclaudio** [globocom/glbgelf#4]
Hello,

Currently you're importing the GELF lib (`github.com/Graylog2/go-gelf/gelf﻿`). That's a legacy API (v1) and have a limited support (only UDP, e.g.). It would be nice if you import the GELF lib v2 (`gopkg.in/Graylog2/go-gelf.v2/gelf`).

**Comment by carlosljr** [comment]
This [pull request](https://github.com/globocom/glbgelf/pull/6) addresses this issue.
